author: MatteoH2O1999
name: "Setup Python"
branding:
  icon: play-circle
  color: blue
description: "Set up a specific version of Python (building from source if deprecated) and add the command-line tools to the PATH."
inputs:
  python-version:
    description: "Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset."
  python-version-file:
    description: "File containing the Python version to use. Example: .python-version"
  cache:
    description: "Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry."
    required: false
  architecture:
    description: "The target architecture (x86, x64) of the Python or PyPy interpreter."
  check-latest:
    description: "Set this option if you want the action to check for the latest available version that satisfies the version spec."
    default: false
  token:
    description: "The token used to authenticate when fetching Python distributions from https://github.com/actions/python-versions. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting."
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  cache-dependency-path:
    description: "Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies."
  update-environment:
    description: "Set this option if you want the action to update environment variables."
    default: true
  cache-build:
    required: false
    description: Whether to cache the built Python distribution to speed up successive runs (true or false, defaults to false).
    default: false
  allow-build:
    required: false
    description: "Set the behavior of the actoin when actions/setup-python fails and has to build from source. Supported values: allow, info, warn, error"
    default: warn
outputs:
  python-version:
    description: "The installed Python or PyPy version. Useful when given a version range as input."
    value: ${{ steps.setup.outputs.python-version }}
  cache-hit:
    description: "A boolean value to indicate a cache entry was found"
    value: ${{ steps.setup.outputs.cache-hit }}
  python-path:
    description: "The absolute path to the Python or PyPy executable."
    value: ${{ steps.setup.outputs.python-path }}
runs:
  using: composite
  steps:
    - name: Check if Python version is deprecated and eventually build it
      run: echo "build"
      shell: pwsh
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      id: setup
      with:
        python-version: ${{ inputs.python-version }}
        python-version-file: ${{ inputs.python-version-file }}
        cache: ${{ inputs.cache }}
        architecture: ${{ inputs.architecture }}
        check-latest: ${{ inputs.check-latest }}
        token: ${{ inputs.token }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        update-environment: ${{ inputs.update-environment }}