name: Periodic UX check

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
      

jobs:
  # Create strategy matrix with a python script
  create_matrix:
    name: Create matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-json: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install wheel
        run: pip install wheel
      - name: Install requirements
        run: pip install -r ./.github/scripts/requirements.txt
      - name: Create matrix
        id: matrix
        run: python ./.github/scripts/create_python_matrix.py
  
  # Test the action with all possible combinations of python versions and os
  test_action:
    needs: create_matrix
    runs-on: ${{ matrix.os }}
    name: Test setup Python ${{ matrix.python-version }} for ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.create_matrix.outputs.matrix-json) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v0
        with:
          python-version: ${{ matrix.python-version }}
          allow-build: info
      - name: Check Python version
        run: python ./.github/scripts/check_python_version.py ${{ matrix.python-version }}