name: Release action

on:
  release:
    types:
      - "created"

jobs:
  # Update tags
  update_tags:
    runs-on: ubuntu-latest
    name: Update version tags
    permissions:
      contents: write
    steps:
      - name: Update tags
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.event.release.tag_name }}
